# Generated by Django 4.1 on 2023-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tips',
            field=models.TextField(max_length=2000),
        ),
    ]
